// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKdWThyzGFHu5FiW6t1c_ZmlNRXcTVdmA',
    appId: '1:721330667817:web:1ed0915a1e90d139e6b738',
    messagingSenderId: '721330667817',
    projectId: 'lttbdd-73c31',
    authDomain: 'lttbdd-73c31.firebaseapp.com',
    storageBucket: 'lttbdd-73c31.firebasestorage.app',
    measurementId: 'G-REQVG8GL44',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnzcLeFjFK3gjwDTvHzTNFTFo2X-tH7Xk',
    appId: '1:721330667817:android:6fbe761309c5eb53e6b738',
    messagingSenderId: '721330667817',
    projectId: 'lttbdd-73c31',
    storageBucket: 'lttbdd-73c31.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvVQyecflPl1cQfiQOWcad4LrmPv16l2M',
    appId: '1:721330667817:ios:5fa9bf5327cbfd5ce6b738',
    messagingSenderId: '721330667817',
    projectId: 'lttbdd-73c31',
    storageBucket: 'lttbdd-73c31.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvVQyecflPl1cQfiQOWcad4LrmPv16l2M',
    appId: '1:721330667817:ios:5fa9bf5327cbfd5ce6b738',
    messagingSenderId: '721330667817',
    projectId: 'lttbdd-73c31',
    storageBucket: 'lttbdd-73c31.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKdWThyzGFHu5FiW6t1c_ZmlNRXcTVdmA',
    appId: '1:721330667817:web:08c66ec8430f1167e6b738',
    messagingSenderId: '721330667817',
    projectId: 'lttbdd-73c31',
    authDomain: 'lttbdd-73c31.firebaseapp.com',
    storageBucket: 'lttbdd-73c31.firebasestorage.app',
    measurementId: 'G-EZMKDCKNJP',
  );
}
